version: '3'

services:
  mongo:
    image: mongo:4.2.0
    container_name: notify_watcher-mongo
    restart: always
    expose:
      - 27017
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/config:/data/configdb

  mongoui:
    image: mongo-express:0.49.0
    container_name: notify_watcher-mongoui
    restart: always
    depends_on:
      - mongo

  redis:
    image: redis:5.0.3
    container_name: notify_watcher-redis
    restart: always
    expose:
      - 6379
    volumes:
      - ./redis/data:/data

  redisui:
    image: rediscommander/redis-commander:latest
    container_name: notify_watcher-redisui
    restart: always
    depends_on:
      - redis

  server:
    image: notifywatcher1/server:latest
    container_name: notify_watcher-api
    restart: always
    depends_on:
      - mongo
